version: '3'

services:

  a-server:
    build:
      context: ./aServer
      dockerfile: dockerfile
    ports:
      - "8187:8187"
    environment:
      - B_SERVER_URL=http://b-server:8188
    depends_on:
      - b-server

  b-server:
    build:
      context: ./aServer
      dockerfile: dockerfile
    ports:
      - "8188:8188"